name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  triage:
    if: github.actor == 'dependabot[bot]'
    uses: flipslidersand-labs/qa-workflows/.github/workflows/dependabot-auto-merge.yml@5f38244e9beed38126f1ef0f8bf868e671c0fba2 # qa-workflows#39 (squash merge)
